### ISSUE TITLE
Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by JaapWeijland** [hasanayan/craco-plugin-single-spa-application#3] opened 2021-03-10 13:00 UTC
Hi there,

I used your script to compile my React app to a single bundle in order to load in conventiently as a web component. However, when I do so, the host page outputs the following:

`<...> Uncaught ReferenceError: System is not defined`

My configuration looks as follows:

```
singleSpaApplicationPlugin = require('craco-plugin-single-spa-application');

module.exports = {
    style: {
        postcss: {
            plugins: [require('tailwindcss'), require('autoprefixer')],
        },
    },
    plugins: [
        {
            plugin: singleSpaApplicationPlugin,
            options: {
                orgName: '...',
                projectName: '...',
                entry: 'src/index.tsx',
                orgPackagesAsExternal: false,
                reactPackagesAsExternal: false,
                minimize: false
            },
        },
    ],
};
```

Any idea?

**Comment by hasanayan** [comment] 2021-03-10 14:50
seems like a problem with your host application

**Comment by hasanayan** [comment] 2021-03-22 20:30
closing as it seems the issue is not related to this plugin. feel free to reopen if you find some new information on the issue.

**Closed by hasanayan** 2021-03-22 20:30 UTC

**Comment by m0ddixx** [comment] 2021-04-16 13:20
I do get the same error. Could it be something to with yarn? The craco.config.js doesn't contain anything else

**Comment by JaapWeijland** [comment] 2021-04-21 11:26
I wanted to use this to create a single page application within a web component, but it turned out this package is only usable when you use the "single-spa" framework, which I didn't. That's why it didn't work probably.

**Comment by DavisAre** [comment] 2022-08-05 09:01
> I wanted to use this to create a single page application within a web component, but it turned out this package is only usable when you use the "single-spa" framework, which I didn't. That's why it didn't work probably.

This is also unexpected surprise to me. Since I thought I thought it was just shorter term for "Single-page application", not a reference to https://single-spa.js.org/.
@JaapWeijland Did you found other solution that worked for you? Currently in the same situation - would like to bundle create-react-app as a single file to be embedded within existing site.
